language: csharp
solution: UrlShortener.sln
mono: none
dotnet: 3.1
install:
- dotnet restore

script:
 - dotnet build
 - dotnet test tests/UrlShortener.Services.Tests/UrlShortener.Services.Tests.csproj
