language: csharp
solution: UrlShortener.sln
dotnet: 3.1.0
install:
  - nuget restore UrlShortener.sln
  - nuget install NUnit.Console -Version 3.11.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release UrlShortener.sln