services:
  urlshortener:
    restart: always
    container_name: urlshortener-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:80
    env_file:
    - compose.env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0-debian
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: urlshortener
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ~/.docker/mysql/data:/var/lib/mysql